debug: false
management.endpoints.web.exposure.include: "*"

logging:
  level:
    kr.semanticker.projectboard: debug
    org.springframework.web.servlet: debug
    org.hibernate.type.descriptor.sql.BasicBinder: trace

spring:
  datasource:
#    url: jdbc:mysql://ip:port/board
#    username: username
#    password: password
#    driver-class-name: com.mysql.cj.jdbc.Driver

    url: jdbc:h2:mem:testdb;mode=mysql
    username: sa
    driverClassName: org.h2.Driver

  jpa:
    defer-datasource-initialization: true
    hibernate.ddl-auto: create
    #open-in-view: false
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 100
  # h2.console.enabled: true
  sql.init.mode: always
  data.rest:
    base-path: /api
    detection-strategy: annotated
  # thymeleaf.cache: false
  # data.rest:
  #     base-path: /api
  #    detection-strategy: annotated
  config:
    activate:
      on-profile:

---

spring:
  config.activate.on-profile: testdb
#  datasource:
#    url: jdbc:h2:mem:board;mode=mysql
#    driverClassName: org.h2.Driver
#  sql.init.mode: always
#  test.database.replace: none

